version: '3'

services:
  app:
    build: .
    ports: 
      - "8080:80"
    tty: true
    volumes:
      - ./:/usr/share/nginx
    networks: 
      - app-network
    depends_on:
      - "mysql-app"
      
  redis-app:
    image: redis
    command: redis-server --requirepass upd@ter2019
    ports:
      - "6379:6379"
    networks: 
      - app-network

  mysql-app:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: updater
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge